### ISSUE TITLE
Push Gateway returning 400 error

### ISSUE THREAD

**Issue by dinumathai** [dhatim/dropwizard-prometheus#1]
For the below code prometheus api gateway is returning HTTP 400 error
Push Gateway Version : **0.4.0**
**Code :** 
 PrometheusSender pushgateway = new Pushgateway("localhost", 9091);
if (!pushgateway.isConnected()) {
	pushgateway.connect();
}
Counter counter = new Counter();
counter.inc();
pushgateway.sendCounter("test-counter", counter);
pushgateway.flush();
pushgateway.close();

**Comment by Albatarm** [comment]
I just update plugin version of maven script.
I test with the given source. But I didn't get HTTP 400 error.
Could you tell me if you can reproduce with the master branch ?

**Comment by dinumathai** [comment]
My Bad. It worked when I restated my pushgateway.
